config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- css -->
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <!-- JavaScript -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Complemento Bootstrap popper-javascript-jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">      
      <nav class="navbar navbar-inverse navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand">My Fist App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to 'One', pages_one_path, class:"nav-item nav-link" %>   
            <%= link_to 'Two', pages_two_path, class:"nav-item nav-link" %>   
            <%= link_to 'Three', pages_three_path, class:"nav-item nav-link" %>          
          </div>
        </div>
      </nav>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/one.html.erb
<h1>ALVARO LUIS RIVAS</h1>

app/views/pages/three.html.erb
<h2>PAGINA 3</h2>
<p>Lorem ipsum dolor sit amet, urna id, dui fermentum sed venenatis auctor, amet sed aliquam nunc accumsan wisi urna. Siéntese elit vulputate pharetra facilisis orci tellus, sed sit elit risus convallis en erat, et quis leo quisque tellus ornare sit, habitasse urna quisque. Portero veniam nulla arcu nam. Suspendisse wisi etiam nisl erat sapien imperdiet. Quam dui nunc velit porttitor, nunc nulla. Quis viverra vitae duis placerat et. Non at proin elit eu, ipsum suspendisse erat odio aliquam arcu eu, tempor non nulla aliquet donec fringilla urna, quis wisi at nec, arcu et. Vestibulum donec nunc venenatis en vulputate.</p>

app/views/pages/two.html.erb
<%= image_tag 'rake_route.jpeg', class:"img-fluid" %>